name: 'Analogicus Janeway GDS Action'
description: 'This action generates a GDS'
branding:
  color: purple
  icon: layers

inputs:
  cell:
    description: 'Name of cell'
    required: true
    type: string
  library:
    description: 'Name of library'
    required: true
    type: string


runs:
    using: 'composite'
    steps:
      - name: Checkout tech
        shell: bash
        run: cd ../ && git clone https://github.com/wulffern/tech_sky130A.git && git clone https://github.com/wulffern/tech_sky130B.git
      - name: Run GDS
        shell: bash
        env:
          CELL: ${{ inputs.cell }}
          LIBRARY: ${{ inputs.library }}
        run: |
          export PDK_ROOT=/opt/pdk/share/pdk
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "/opt/eda/bin" >> $GITHUB_PATH
          cd work; make gds CELL=$CELL LIB=$LIBRARY
          export
          test -f work/gds/${CELL}.gds || exit 1;
      - name: Archive GDS
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            work/gds/${{ inputs.cell }}.gds
            work/gds/${{ inputs.cell }}.log
